import { useTranslation } from 'next-i18next';
import Head from 'next/head';
import Image from 'next/image';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { GetServerSideProps, GetStaticProps } from 'next';
import { useQuery } from 'react-query';

import styles from '../styles/Home.module.css';

export default function Home({ data: dataFetch }: any) {
  const { t } = useTranslation('common');

  const { data, status } = useQuery(`episode-${1}`, async () =>
    (await fetch(`https://rickandmortyapi.com/api/episode/${1}`)).json()
  );

  if (dataFetch) {
    return <pre>{JSON.stringify(dataFetch)}</pre>;
  }

  if (status === 'loading') {
    return <p>Loading...</p>;
  }
  if (status === 'error') {
    return <p>Error :(</p>;
  }

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        {/* TODO: Change title */}
        <title>React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {JSON.stringify(data)}
      <main className={styles.main}>
        {t('hello')}
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// TODO: only one method
// export const getStaticProps: GetStaticProps = async ({ locale }) => ({
//   props: {
//     ...(await serverSideTranslations(locale, ['common']))
//   }
// });

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  const data = await (await fetch(`https://rickandmortyapi.com/api/episode/${1}`)).json();

  return {
    props: {
      data,
      ...(await serverSideTranslations(locale, ['common']))
    }
  };
};
